
const config = require(`./${HUZAN_ENV}.js`).default

export default Object.assign({
    apiHost: '',
    accessTokenKey: 'HUZAN_ACCESS_TOKEN_KEY',
    globalPagePaths: [
        '/find_password',
        '/login',
        '/register',
        '/register/agreement',
        '/platform/voice_packets/wechatPay',
        '/mall/agreement',
        '/setting/oauth_result',
        '/setting/oauth_agreement',
        '/setting/oauth_agreement/detial',
        '/platform/voice_packets/agreement',
        '/setting/authorization/oauthresult',
        '/setting/version_information/charge/wechat',
        '/setting/version_information/charge/publictransfer',
        '/403',
        '/demo/qiniu_upload',
        '/shop_fitment',
        '/open/qidian',
        '/open/guidance',
        '/agreement/commodityRule',
        '/agreement/messageRule',
        '/auto_login',
    ],
    ignoreCheckPagesPermissionPaths: [
        '/app/:id',
        '/app_preview',
        '/find_password',
        '/login',
        '/register',
        '/register/agreement',
        '/platform/voice_packets/wechatPay',
        '/mall/agreement',
        '/setting/oauth_result',
        '/setting/oauth_agreement',
        '/setting/oauth_agreement/detial',
        '/platform/voice_packets/agreement',
        '/setting/authorization/oauthresult',
        '/demo/upload',
        '/403',
        '/setting/version_information/charge/wechat',
        '/setting/version_information/charge/publictransfer',
        '/',
        '/demo/qiniu_upload',
        '/shop_fitment',
        '/setting/notice',
        '/setting/notice/detail',
        '/open/qidian',
        '/open/guidance',
        '/agreement/commodityRule',
        '/agreement/messageRule',
        '/auto_login',
    ],
    hiddenMenuForPath: [],
    niukefuUrl: '',
}, config)
